// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: google/ads/googleads/v18/services/user_list_customer_type_service.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserListCustomerTypeServiceClient is the client API for UserListCustomerTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserListCustomerTypeServiceClient interface {
	// Attach or remove user list customer types. Operation statuses
	// are returned.
	//
	// List of thrown errors:
	//
	//	[AuthenticationError]()
	//	[AuthorizationError]()
	//	[UserListCustomerTypeError]()
	//	[HeaderError]()
	//	[InternalError]()
	//	[QuotaError]()
	//	[RequestError]()
	MutateUserListCustomerTypes(ctx context.Context, in *MutateUserListCustomerTypesRequest, opts ...grpc.CallOption) (*MutateUserListCustomerTypesResponse, error)
}

type userListCustomerTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserListCustomerTypeServiceClient(cc grpc.ClientConnInterface) UserListCustomerTypeServiceClient {
	return &userListCustomerTypeServiceClient{cc}
}

func (c *userListCustomerTypeServiceClient) MutateUserListCustomerTypes(ctx context.Context, in *MutateUserListCustomerTypesRequest, opts ...grpc.CallOption) (*MutateUserListCustomerTypesResponse, error) {
	out := new(MutateUserListCustomerTypesResponse)
	err := c.cc.Invoke(ctx, "/google.ads.googleads.v18.services.UserListCustomerTypeService/MutateUserListCustomerTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserListCustomerTypeServiceServer is the server API for UserListCustomerTypeService service.
// All implementations must embed UnimplementedUserListCustomerTypeServiceServer
// for forward compatibility
type UserListCustomerTypeServiceServer interface {
	// Attach or remove user list customer types. Operation statuses
	// are returned.
	//
	// List of thrown errors:
	//
	//	[AuthenticationError]()
	//	[AuthorizationError]()
	//	[UserListCustomerTypeError]()
	//	[HeaderError]()
	//	[InternalError]()
	//	[QuotaError]()
	//	[RequestError]()
	MutateUserListCustomerTypes(context.Context, *MutateUserListCustomerTypesRequest) (*MutateUserListCustomerTypesResponse, error)
	mustEmbedUnimplementedUserListCustomerTypeServiceServer()
}

// UnimplementedUserListCustomerTypeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserListCustomerTypeServiceServer struct {
}

func (UnimplementedUserListCustomerTypeServiceServer) MutateUserListCustomerTypes(context.Context, *MutateUserListCustomerTypesRequest) (*MutateUserListCustomerTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MutateUserListCustomerTypes not implemented")
}
func (UnimplementedUserListCustomerTypeServiceServer) mustEmbedUnimplementedUserListCustomerTypeServiceServer() {
}

// UnsafeUserListCustomerTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserListCustomerTypeServiceServer will
// result in compilation errors.
type UnsafeUserListCustomerTypeServiceServer interface {
	mustEmbedUnimplementedUserListCustomerTypeServiceServer()
}

func RegisterUserListCustomerTypeServiceServer(s grpc.ServiceRegistrar, srv UserListCustomerTypeServiceServer) {
	s.RegisterService(&UserListCustomerTypeService_ServiceDesc, srv)
}

func _UserListCustomerTypeService_MutateUserListCustomerTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateUserListCustomerTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserListCustomerTypeServiceServer).MutateUserListCustomerTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.googleads.v18.services.UserListCustomerTypeService/MutateUserListCustomerTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserListCustomerTypeServiceServer).MutateUserListCustomerTypes(ctx, req.(*MutateUserListCustomerTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserListCustomerTypeService_ServiceDesc is the grpc.ServiceDesc for UserListCustomerTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserListCustomerTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.ads.googleads.v18.services.UserListCustomerTypeService",
	HandlerType: (*UserListCustomerTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MutateUserListCustomerTypes",
			Handler:    _UserListCustomerTypeService_MutateUserListCustomerTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/ads/googleads/v18/services/user_list_customer_type_service.proto",
}
